#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║        🎮 RETRO ARCADE - APK BUILD LAUNCHER 🎮              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ All code is committed and pushed to GitHub"
echo "✅ EAS Build is configured and ready"
echo "✅ Project is linked to Expo"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📱 STEP-BY-STEP: GET YOUR APK"
echo ""
echo "1️⃣  Open this URL in your mobile browser:"
echo "    https://expo.dev/accounts/twskoops/projects/retro-arcade/builds"
echo ""
echo "2️⃣  Tap 'Create a build' (blue button)"
echo ""
echo "3️⃣  Select:"
echo "    • Platform: Android"
echo "    • Profile: preview"
echo ""
echo "4️⃣  When asked about Android Keystore:"
echo "    • Tap 'Generate new keystore'"
echo "    • Tap 'Next' / 'Create'"
echo ""
echo "5️⃣  Build starts automatically!"
echo "    • Runs on GitHub/EAS servers"
echo "    • Takes ~15-20 minutes"
echo "    • You'll see real-time logs"
echo ""
echo "6️⃣  When complete:"
echo "    • Download button appears"
echo "    • Tap to download APK"
echo "    • Install on your device!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Monitor build from Termux:"
echo ""
echo "    eas build:list --platform android"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press ENTER to check if build has started..."
echo ""
echo "Checking for active builds..."
eas build:list --platform android --limit 5
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If no builds are listed, start one using the web dashboard!"
echo ""
echo "Direct link: https://expo.dev/accounts/twskoops/projects/retro-arcade/builds"
echo ""
