// Apple IIe authentic color palette
export const COLORS = {
  BLACK: '#000000',
  WHITE: '#FFFFFF',
  GREEN: '#00FF00',
  PURPLE: '#FF00FF',
  ORANGE: '#FF8800',
  BLUE: '#0088FF',
};

export const RETRO_PALETTE = [
  COLORS.BLACK,
  COLORS.WHITE,
  COLORS.GREEN,
  COLORS.PURPLE,
  COLORS.ORANGE,
  COLORS.BLUE,
];

// UI Color scheme
export const UI_COLORS = {
  BACKGROUND: COLORS.BLACK,
  PRIMARY: COLORS.GREEN,
  SECONDARY: COLORS.ORANGE,
  DANGER: COLORS.PURPLE,
  INFO: COLORS.BLUE,
  TEXT: COLORS.WHITE,
  TEXT_MUTED: COLORS.GREEN,
};
